feat: vip currency removed
InsertCoinAB/gwen-react-components pull request #686
Opened 2021-09-30 14:41 UTC by christianinsert

2021-10-04 08:58 UTC, OstwaldT requested changes

2021-10-04 08:58 UTC, OstwaldT commented on src/shop/utils/parse-currency.ts
>  }
This function looks to be pointless now. Should be removed right?

2021-10-04 09:02 UTC, christianinsert commented on src/shop/utils/parse-currency.ts
>  }
Well, of course, it's pointless like that. But I was thinking about progression as currency. I want to remember that we wanted to add the possibility in admin to set a human readable translation for each progression currency - once we do that, these functions will be the place to do that. That's why I think they are worth keeping.

2021-10-04 12:47 UTC, Hagej approved these changes

2021-10-05 11:41 UTC, OstwaldT commented on src/shop/utils/parse-currency.ts
>  }
This should still result in a lint-error due to not using the in-parameter. Anyhow we should remove this function until we have a use for it.

2021-10-05 14:02 UTC, OstwaldT approved these changes

2021-10-05 14:02 UTC, merged